### ISSUE TITLE
Is partials option relative to target template or root dir

### ISSUE THREAD

**Issue by xcatliu** [queckezz/koa-views#101]
Hi, I saw there is a `partials` option which can set handlebars partial.
I expect it to be relative to the root dir that I passed to `views()`, but it seems it's relative to the target template?

For example, I have the configuration like this:

```js
const app = new Koa()
  .use(views('lib/views', {
    map: { hbs: 'handlebars' },
    options: {
      partials: {
        head: './partials/head'
      }
    }
  }));
```

`lib/views/partials/head.hbs`:

```hbs
<head>
  <title>Hello World</title>
</head>
```

`lib/views/index.hbs`:

```hbs
<!DOCTYPE html>
<html>
  {{> head }}
  <body>
    <h1>Index</h1>
  </body>
</html>
```

`lib/views/pages/new.hbs`:

```hbs
<!DOCTYPE html>
<html>
  {{> head }}
  <body>
    <h1>New</h1>
  </body>
</html>
```

It works fine with `lib/views/index.hbs`, but got error from `lib/views/pages/new.hbs`:

```bash
Error: ENOENT: no such file or directory, open '...\lib\views\pages\partials\head.hbs'
```

**Comment by int64ago** [comment]
Yes.
> koa-views is using consolidate under the hood.

Actually, it's the behavior of [consolidate](https://github.com/tj/consolidate.js/blob/master/lib/consolidate.js#L121).

**Comment by xcatliu** [comment]
@int64ago Thanks. But I still have the question, how should I include partials in templates with different dirpath?

`lib/views/partials/head.hbs`
`lib/views/index.hbs`
`lib/views/pages/new.hbs`

In the above case, both `lib/views/index.hbs` and `lib/views/pages/new.hbs` needs to include the partial `lib/views/partials/head.hbs`

**Comment by int64ago** [comment]
Seems there's no appropriate way, maybe a PR to consolidate can make it work

**Comment by int64ago** [comment]
Closed, feel free to open it again if necessary.
