### ISSUE TITLE
Need koa-views only only a few routes

### ISSUE THREAD

**Issue by wlingke** [queckezz/koa-views#102]
Suppose I have a bunch of routes - /a, /b, /c, /d, /e, /f, /g ..., but only routes /a and /b will ever render any pages.

Is it better to call `app.use(views(..))` at the top of my server (before any routes are defined) OR is it better to call `app.use('/a', mount(views(...)))` - ie only at the top of the routes that need it?

**Comment by int64ago** [comment]
Does this work for you ?
```
app.use(async (ctx, next) => {
  if (shouldRender(ctx.path)) {
     await ctx.render();
  } else {
    await next();
  }
})
```

Here `shouldRender` is your route rules.

**Comment by wlingke** [comment]
Yea I was planning to `ctx.render` based on route anyways, but I was wondering if it was better to load the `app.use(views)` only on routes that needed it

**Comment by int64ago** [comment]
You can directly render specific route by
```
app.use('/a', async ctx => {
  await ctx.render();
})
```

**Comment by wlingke** [comment]
okay thanks!
