### ISSUE TITLE
get-paths need node >=8.3?

### ISSUE THREAD

**Issue by webkixi** [queckezz/koa-views#109]
oh no~~, my node version was 7.10.0. what the improvement about koa-views 6.1.0?

**Comment by avindra** [comment]
@webkixi You should upgrade to 8.3.x or higher as 7 is end of life.

@queckezz Can we get a summary of what's changed in 6.1.0 and why 8.3 is now a requirement?

**Comment by avindra** [comment]
Upstream PR made here

https://github.com/niftylettuce/get-paths/pull/1

cc @niftylettuce

**Comment by niftylettuce** [comment]
Almost done with the fix

**Comment by niftylettuce** [comment]
@avindra @webkixi see #110
