### ISSUE TITLE
Why don't you assign "locals" to "ctx.state"?

### ISSUE THREAD

**Issue by fengxinming** [queckezz/koa-views#113]
origin:
`const state = Object.assign(locals, options, ctx.state || {})`

turn into:
`const state = Object.assign({}, options, ctx.state || {}, locals)`
Would it be better?

**Comment by int64ago** [comment]
@fengxinming hi, any case to prove ?

**Comment by int64ago** [comment]
@fengxinming Hi, I think this is a break change, and `options` should not be covered by `locals`

**Comment by fengxinming** [comment]
@int64ago or `locals` cover `options`

**Comment by Yaojian** [comment]
`const state = Object.assign(locals, options, ctx.state || {})` may lead bug when `locals` is contained (directly or indirectly) by `ctx.state`, the `assign` call will cause `locals` contains circular references.
