### ISSUE TITLE
Add file path to ctx

### ISSUE THREAD

**Issue by jgdev** [queckezz/koa-views#115]
I have a logger middleware, I would like to know what file was rendered in the end of the response.

**Comment by int64ago** [comment]
@jgdev Hi, any code snippet? Actually, `koa-views` ONLY add a `render` method in ctx, I don't think it has any relation to your logger middleware.

**Comment by jgdev** [comment]
https://github.com/queckezz/koa-views/blob/db8a41e9ee2210f2ae4a951ebc7bc554699b5ea0/src/index.js#L42-L50

I just want to create an instance of the value `resolve(path, paths.rel)` in somewhere, maybe `ctx.renderPath`.
