### ISSUE TITLE
Why do I have to call 'return' on ctx.render

### ISSUE THREAD

**Issue by rocketspacer** [queckezz/koa-views#118]
Why does this works:
```
app.use((ctx, next) => {
  return ctx.render('user', { user }); // return is important, I don't know why
});
```
and this doesn't:
```
app.use((ctx, next) => {
  ctx.render('user', { user }); // Response 404
});
```

**Comment by int64ago** [comment]
https://github.com/koajs/koa/blob/master/lib/application.js#L113

https://github.com/koajs/koa/blob/master/lib/application.js#L126

https://github.com/koajs/compose/blob/master/index.js#L42

The callback in `use` should be in synchronous (like `async/await`) or return a Promise
