### ISSUE TITLE
How can i add a config?

### ISSUE THREAD

**Issue by shalldie** [queckezz/koa-views#120]
For example , i init like this:
```js
app.use(views(path.join(__dirname, 'views'), {
    map: { html: 'nunjucks' }
}));
```
But where do i add the nunjucks' config?

**Comment by int64ago** [comment]
Here's an example: https://github.com/queckezz/koa-views/blob/master/test/index.js#L277

**Comment by shalldie** [comment]
Thanks a lot. 
:D
