### ISSUE TITLE
Getting a template not found error when I use nunjucks base layouts with co-views in koa

### ISSUE THREAD

**Issue by damaohub** [queckezz/koa-views#121]
Like the question in stackoverflow,[the link](https://stackoverflow.com/questions/33156092/getting-a-template-not-found-error-when-i-use-nunjucks-base-layouts-with-co-view).
Would you  help me with some advice?
Thanks.

**Comment by int64ago** [comment]
This's the repo of koa-views not [co-views](https://github.com/tj/co-views)
