### ISSUE TITLE
a proposal

### ISSUE THREAD

**Issue by Dec-F** [queckezz/koa-views#125]
It is recommended to add a configuration item and mount the path of the template file to ctx. 

This can support some hacks in the development environment, such as reading the template file compiled by webpack in memory. 

I think this is a very common requirement in development. What do you think, if I can mention a PR?

**Comment by int64ago** [comment]
Cloud you give an example to explain it? I don't understand the relation between `the template file compiled ` and `path of the template file`.

**Comment by Dec-F** [comment]
I did not think clearly, I have found another way to solve the problem.

**Comment by ckrad** [comment]
hello my template file is in memory how can i read it?

**Comment by Dec-F** [comment]
@ckrad  If you are using webpack packaged, you can look at the API of [this package](https://github.com/webpack/memory-fs).
