### ISSUE TITLE
consolidate.js is currently at v0.15.4 (npm repository is at v0.15.1)

### ISSUE THREAD

**Issue by arizvisa** [queckezz/koa-views#129]
As mentioned in the title, the `consolidate.js` module has a newer (major) version than what `koa-views` depends on by default.

Maybe it's not too important, but the v0.15 series of `consolidate.js` has support for `swig-templates`. The original `swig` module is unmaintained and was forked into a maintained version, `swig-templates`. And thus, `swig-templates` is the module that people should be using from here-on-out.

The fix for this is to simply crank up the version in `package.json `to something in the v0.15 series (likely v0.15.1 since that's the latest in the npm repo as of today).

**Comment by arizvisa** [comment]
As a workaround, one can simply add the following under the "resolutions" key in their package.json.
```
"consolidate": "0.15.1"^M
```

**Comment by int64ago** [comment]
Done, thanks :-)
