### ISSUE TITLE
Version bump get-paths and consolidate

### ISSUE THREAD

**Issue by niftylettuce** [queckezz/koa-views#136]
@queckezz @int64ago Can you please version bump get-paths and consolidate?

**Comment by niftylettuce** [comment]
I fixed core bugs in get-paths (e.g. it had an extra dependency not being used of `fs-extra`, and I removed its dependency of `bluebird` and replaced with `pify`).  The package is way more lightweight now.

**Comment by niftylettuce** [comment]
Also if you would like me to help maintain this package, feel free to move it to the @koajs organization on GitHub (or just add me as a collaborator here) and add `niftylettuce` to npm owners.

**Comment by int64ago** [comment]
@niftylettuce 
I've reviewed the changes you made, looks neccessary :+1: I'll do a version bump


> Also if you would like me to help maintain this package ...

Sorry, i have no permission do that, wait for @queckezz

**Comment by int64ago** [comment]
Released via `v6.2.1`

**Comment by niftylettuce** [comment]
Ty 👍
