### ISSUE TITLE
Slow performance with large options object

### ISSUE THREAD

**Issue by matkl** [queckezz/koa-views#139]
Stringifying large objects can be slow. Removing `JSON.stringify()` here makes my renders 20 ms faster.

https://github.com/queckezz/koa-views/blob/cfe7920ce95aad337c74039e447545108983e7cb/src/index.js#L41

**Comment by int64ago** [comment]
Hi, it's not recommend to use debug in production environment.

It's the limit of `debug`, do you have any idea to debug here without `JSON.stringify` ?

**Comment by matkl** [comment]
The problem here is that `JSON.stringify` is called before debug and therefore is called in production environment.

**Comment by matkl** [comment]
OK, I looked up the `debug` documentation and you can check if the debug target is enabled. Wrapping the call with

`
if (debug.enabled) {
  // do stuff...
}
`

will fix the issue.

**Comment by int64ago** [comment]
> The problem here is that JSON.stringify is called before debug and therefore is called in production environment.

Yes, it is. It's because `debug` cannot handle with BigInt, so here we use a replacer back in `JSON.stringify`.

**Comment by int64ago** [comment]
> OK, I looked up the `debug` documentation and you can check if the debug target is enabled. Wrapping the call with
> 
> `if (debug.enabled) { // do stuff... }`
> 
> will fix the issue.

`debug` is enabled only if here's a `DEBUG` environment, so you should not set this environment in production in most cases.

**Comment by matkl** [comment]
Of course I'm not enabling debug in production. The issue is about `JSON.stringify(state, bigIntReplacer())` is called on every render in **production** mode.

**Comment by int64ago** [comment]
Ok, I understand, I'll fix this, thanks :-)

**Comment by int64ago** [comment]
Thanks, released via `v6.2.3`
