### ISSUE TITLE
ctx closure issue for v6.3.0

### ISSUE THREAD

**Issue by alex-zhang** [queckezz/koa-views#147]
hi , 

i want to use the `app.context.render = render()` by koa-views. but there is  ctx closure issue. below.

https://github.com/queckezz/koa-views/blob/f2dca20ddc83733833bbfcdfce942e5d3ad71ea4/src/index.js#L34

i also found, this issue already fix in master branch, pls help to release a new version thanks.

**Comment by int64ago** [comment]
Hi, sorry for this, i have published `v6.3.1`

**Comment by alex-zhang** [comment]
@int64ago  thanks.
