### ISSUE TITLE
Can't I use Eta template engine in koa-views?

### ISSUE THREAD

**Issue by hwanyong** [queckezz/koa-views#162]
Can't I use Eta template engine in koa-views? In this case, should I directly link with eta using eta-views-render?

![image](https://user-images.githubusercontent.com/7351956/150001893-ca8a4d22-701b-4a60-9a09-c2a5a6cb1add.png)

**Comment by niftylettuce** [comment]
This package internally uses `consolidate` @ https://github.com/tj/consolidate.js.

The issue is most likely that `consolidate` doesn't support `eta` or vice-versa.
