### ISSUE TITLE
How I render the subtemplate?

### ISSUE THREAD

**Issue by kiwifly** [queckezz/koa-views#22]
If I have three templates: header.html, footer.html and main.html, how I render the three views? I know co-views could, but I don't know how koa-views? thanks~
The below is the co-views example.
co(function *(){
  var a = render('user', { user: tobi });
  var b = render('user.jade', { user: loki });
  var c = render('user.ejs', { user: luna });
  var html = yield [a, b, c];
  html = html.join('');
  console.log(html);
})();

**Comment by demohi** [comment]
You can't do that. If you need render the subtemplate，you can use co-views. But I think template engine's Partials and Layouts may be better.

**Comment by queckezz** [comment]
Yea this is not possible since `koa-views` sends the html as soon as you `yield`. As @demohi said, you are maybe better off by using `co-views` directly
