### ISSUE TITLE
Using module.parent makes it rather difficult for the package to be used as another package

### ISSUE THREAD

**Issue by shekhei** [queckezz/koa-views#30]
Imagine the following case, where website depends on a meshup of koa and this meshup contains koa-views

website
 |- koameshup
    |-koa
    |-koa-views

the code currently depends on module.parent for base, this will use koameshup's base, which would be
./website/node_modules/koameshup/[path] and this wouldnt work very well.

**Comment by queckezz** [comment]
Is there an alternative for using `module.parent` maybe just use `process.cwd()`.? I'm not sure what would be suitable for the majority of users

**Comment by shekhei** [comment]
Hmm.. I am actually using process.cwd() in my own fork, but I dont think its that appropriate either.

Perhaps at least it could be configured? I've seen some that uses module.parents and keep traversing till it finds one that its "least deep" with a package.json.

**Comment by coderhaoxin** [comment]
maybe `process.cwd()` is better, but it's `broken`. (If so, need publish a major version: 4.x.y)

**Comment by queckezz** [comment]
This should be solved with #35, right?
