### ISSUE TITLE
What is the equivalent to Express's `app.locals`

### ISSUE THREAD

**Issue by Gacnt** [queckezz/koa-views#45]
I'm trying to pass the session to the jade templates so I can check things e.g. authentication, userlevel, so on so forth, but I can't for the life of me figure out how to pass it to `locals` from a middleware, e.g. in my express 4 app:
```
app.use((req, res, next) => {
   app.locals.req = req;
   next();
});
```

now in Koa2
```
app.use(async (ctx, next) => {
	try {
		console.log(ctx.req.locals);
		console.log(ctx.req.state);
                console.log(ctx.state);
                console.log(ctx);
		ctx.state.session = ctx.session;
		await next();
	} catch(err) {
		ctx.body = { message: err.message };
		ctx.status = err.status || 500;
	};
});
```

**Comment by Gacnt** [comment]
Nevermind, second time around ctx.state seemed to work, must have not saved and compiled or something, my mistake

**Comment by queckezz** [comment]
Cool, feel free to ask if something doesn't work!
