### ISSUE TITLE
state won't pass if no locals are passed

### ISSUE THREAD

**Issue by naxmefy** [queckezz/koa-views#46]
This line breaks my expected behavior: https://github.com/queckezz/koa-views/blob/master/index.js#L110

```JavaScript
var state = locals && this.state ? Object.assign(locals, this.state) : {}
```

if locals is undefined or null - state becomes an empty object...
but what if i put information to state but nothing to locals? then i won't got in my views.

**Comment by d6u** [comment]
+1 If author this should be fixed, I can create a PR.

**Comment by naxmefy** [comment]
PR already created

**Comment by naxmefy** [comment]
PR https://github.com/queckezz/koa-views/pull/47
