### ISSUE TITLE
@f/defaults

### ISSUE THREAD

**Issue by liamqma** [queckezz/koa-views#50]
Would you mind telling me what  '@f/defaults' is in the package.json?

When I tries to do 'npm install koa-views@latest', it throws error 

`unregistered users are not allowed to access package @f/defaults : @f/defaults`

**Comment by naxmefy** [comment]
hmm strange - that should be public - the owner fails with naming

a good alternative would be [lodash assignWith](https://lodash.com/docs#assignWith)

example from docs

```JavaScript
var _ = require('lodash');

function customizer(objValue, srcValue) {
  return _.isUndefined(objValue) ? srcValue : objValue;
}

var defaults = _.partialRight(_.assignWith, customizer);

defaults({ 'a': 1 }, { 'b': 2 }, { 'a': 3 });
// → { 'a': 1, 'b': 2 }
```

**Comment by queckezz** [comment]
> Would you mind telling me what '@f/defaults' is in the package.json?

It's a [scoped](https://docs.npmjs.com/misc/scope) package from http://github.com/micro-js

https://github.com/rlidwka/sinopia/issues/243 maybe this will help? I'm not sure if this is related but the resolution works fine for me and for other people using the `@f` org

**Comment by liamqma** [comment]
Hi @queckezz 

Cool. Thanks a lot for your help. I finally get my head around with this scoped package.

Having `always-auth=true` in .npmrc does make sinopia forward authorization, but I still get error

`user liamqma is not allowed to access package @f/defaults : @f/defaults`

I guess it could be something to do with the sinopia config. 

Anyway I will close this ticket because it's irrelevant to this repository.
