### ISSUE TITLE
Update for koa v2

### ISSUE THREAD

**Issue by ifraixedes** [queckezz/koa-views#52]
I took a look the current dependencies and it depends on [co-views](https://github.com/tj/co-views). co-views depends of [co-render](https://github.com/tj/co-render) which relies on [consolidate.js](https://github.com/tj/consolidate.js).

With [koa v2 supporting promises](https://github.com/koajs/koa/tree/2.0.0-alpha.3#example), I don't seen the need to use co-views, because [consolidate.js also returns promises](https://github.com/tj/consolidate.js#promises), so the new version should have a simpler implementation.

I want to know if my thoughts are in the right direction because I may find time to upgrade this modul to create a new version to be used with Koa V2.

**Comment by PlasmaPower** [comment]
Agreed, with `consolidate.js` having [native support for promises](https://github.com/tj/consolidate.js#promises) I don't see the need for `co-views`.

**Comment by queckezz** [comment]
> With koa v2 supporting promises, I don't seen the need to use co-views, because consolidate.js also returns promises, so the new version should have a simpler implementation.

Yea removing `co-views` seems definitely the way to go. PR appreciated!

**Comment by ifraixedes** [comment]
I may try to do the refactoring, however I'm wondering what are your preferences? native Promises or async/await funcs with Babel around?

**Comment by queckezz** [comment]
One thing that has priority is compatibility between the two major versions. I'm really not up to date with how we can make the middleware both compatible with `koa@1` and `koa@2`. Is there even a way or do we have to maintain two seperate branches?

Looking at the soruce of the official Middlewares, I haven't seen any babel pre-compile step so we might want to go with native promises to keep it consistent.

**Comment by ifraixedes** [comment]
The rest of the repos that I've seen which have support for `koa@1` and `koa@2` have 2 different branches; the ones that they have one, offer the possibility to use in `koa@2` with [koa-convert](https://github.com/koajs/convert) however that's the temporary solution until the middleware be migrated.

:+1:  for promises to avoid Babel

**Comment by ifraixedes** [comment]
PR sent #54

**Comment by queckezz** [comment]
`koa@2` now supported, thanks to #54.
