### ISSUE TITLE
5.x or 4.x?

### ISSUE THREAD

**Issue by tunnckoCore** [queckezz/koa-views#56]
It seems v5 is not not published?

**Comment by queckezz** [comment]
```
λ npm install koa-views@next
npm-size@0.0.1 D:\dev\tmp
`-- koa-views@5.0.1  extraneous
```

**Comment by tunnckoCore** [comment]
:laughing: are you serious? I mean.. I'm not using it, just noticed some diffs.

In readme "note" says that master branch is for koa@2, last commit to package.json is v5, npm last published is v4, so what is what? I only understand that v1 branch is for koa@1 and master is for later koa.

But okey, if `next` is v5, what is v4 then? Nevermind, in anyway I don't care, i'm not using it. :)

Cheers,
Charlike!

**Comment by queckezz** [comment]
Yes, that's the way it should be. Everybody who does a `npm install koa-views` should get the version for `koa@1` (which is 4.x). People interested in checking out `koa@2` (which will not be final until v8 native async/await land) can install `koa-views` using the `@next` tag or `5.x`.
