### ISSUE TITLE
ctx.render is not a function

### ISSUE THREAD

**Issue by frontendthug** [queckezz/koa-views#57]
```
// dependencies
import Koa from 'koa';
import jade from 'jade';
import path from 'path';

// middleware dependencies
import Router from 'koa-router';
import views from 'koa-views';
import convert from 'koa-convert';

// init
const app = new Koa();
const router = new Router();

// middlewares
app.use(convert(views(__dirname + '/views', { extension: 'jade' })));
app.use(convert(router.routes())).use(convert(router.allowedMethods()));

// routes
router.get('/', async function (ctx, next) {
  await ctx.render('index');
});

// start app
app.listen(8080);
export default app;
```
What's wrong with this code? I tried different versions, but always get TypeError...

**Comment by queckezz** [comment]
Can you add a failing test? Also if you are using `koa@2` you can use `koa-views@5` as described in the readme instead of `koa-convert`.

```bash
npm install koa-views@next
```

**Comment by frontendthug** [comment]
Where do i need to write tests? It's all code what i have (excluding babel presets/polyfills).
I used both koa v2 + koa-views && koa v2 + koa-views@next... same result.
And sorry, but i really bad in writing tests.... near to zero. :cry:

**Comment by queckezz** [comment]
Your example code works just fine for me. Check out https://github.com/queckezz/koa-views-issue-5. Hopefully this helps!

**Comment by frontendthug** [comment]
hmm.. it works :open_mouth:
very weird.... anyway, it's my fault. Thanks for example! :+1:
