### ISSUE TITLE
Cannot pass a root dir other than __dirname

### ISSUE THREAD

**Issue by isikfsc** [queckezz/koa-views#58]
I am using `koa-views` with `ejs`. I want to put my ejs templates in the views folder in the root dir of my project. When I do this I get an error message saying 
`{ [Error: ENOENT: no such file or directory, open '/Users/isik/Dev/atelye/masteringtrolls/questions.ejs']
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/Users/isik/Dev/atelye/masteringtrolls/questions.ejs' }
`

Actually I see the path stated is incorrect since I wrote it to be in views:
`app.use(views(__dirname + '/views', {
  map: {
    ejs: 'ejs'
  }
}));
`
Is that a bug?

**Comment by jonathanasquier** [comment]
Same here, not taking in account options neither for default file extension for ex
Using this, nothing else works (koa 1, koa-views@1.x)
```
app.use(views());
router
.get('*',
  function* (next) {
    yield this.render('./templates/index.jade');
  }
);

```

**Comment by int64ago** [comment]
@isikfsc Hi, could you give a minimal example and the environments ?

**Comment by int64ago** [comment]
Close for out of date.
