### ISSUE TITLE
new consolidate 0.14.1 has been released and support pug( new jade )

### ISSUE THREAD

**Issue by i5ting** [queckezz/koa-views#61]

**Comment by i5ting** [comment]
see https://github.com/queckezz/koa-views/pull/59

**Comment by queckezz** [comment]
a4dbf404d0a4ed73f25d1b9bed17f2610790486f

**Comment by albertogasparin** [comment]
Can this fix be backported to Koa v1 branch please?

**Comment by i5ting** [comment]
@albertogasparin  1.x depend on co-views,not  consolidate.js , so please wait co-views update

**Comment by albertogasparin** [comment]
@i5ting Thanks for the clarification, will report to co-views then 😉

**Comment by i5ting** [comment]
@albertogasparin already create pr to co-render  https://github.com/tj/co-render/issues/9
