### ISSUE TITLE
[Custom Engine]: allow to override consolidate

### ISSUE THREAD

**Issue by Krisa** [queckezz/koa-views#62]
Eventually, engines are not registered on consolidate and if they don't, there is no way to use them with this module. This is the case of for example [Angular Universal](https://github.com/angular/universal) which has its own Engine and works with Express OOTB without using consolidate like [this](https://github.com/angular/universal-starter/blob/master/src/server.ts#L29). It would be good to be able to do the same in Koa.

**Comment by queckezz** [comment]
Please take a look at https://github.com/queckezz/koa-views/issues/65
