### ISSUE TITLE
Could koa-views return a  template engine object to config(or operate) it?

### ISSUE THREAD

**Issue by Froguard** [queckezz/koa-views#69]
var views = require('koa-views');
    app.use(views(__dirname + '/views', {
      map: {
        html: 'swig'
      }
    }));

I wana get the template engin object (such as swig), to invoke some method of it, such as swig.setFilter(...),but how could I get the template engine object by the variable views ( var views = require('koa-views'); )?

**Comment by Froguard** [comment]
It looks like koa-views return a generator(a function*) to use, I am not able to get the engine boject instance to use some method of engine own.It makes me confused very much...

**Comment by queckezz** [comment]
`koa-views` is using consolidate under the hood. Taking a quick look [at the source](https://github.com/tj/consolidate.js/blob/master/lib/consolidate.js#L403-L416), you can only set the cache. Im using consolidate as a hard dependency. What is not supported there, can't be supported here. 

Maybe something more specific like [koa-swig](https://github.com/koa-modules/swig) makes more sense here.
