### ISSUE TITLE
Doesn't support React v15

### ISSUE THREAD

**Issue by AndreLion** [queckezz/koa-views#71]
Doesn't support `react v15` due to outdated dependency in [consolidate.js](https://github.com/tj/consolidate.js)
Issue: https://github.com/tj/consolidate.js/issues/227
PR: https://github.com/tj/consolidate.js/pull/237

**Comment by queckezz** [comment]
Yes, this is an issue in consolidate and can't be changed here. 

You may wan't to take a look at [koa-react-view](https://github.com/koajs/react-view)
