### ISSUE TITLE
How to use .njk suffix for file name using nunjacks engine?

### ISSUE THREAD

**Issue by farzer** [queckezz/koa-views#84]
```
// views
app.use(views(path.join(__dirname, '../views'), {
  extension: 'nunjucks'
}));
```

my view file is `xxx.njk`

but make error: `... can not found xxx.nunjucks`

**Comment by queckezz** [comment]
```js
app.use(views(path.join(__dirname, '../views'), {
  map: { njk: 'nunjucks' },
  extension: 'njk'
}));
```
whereas `extension` is optional. This is so you can just do `this.render('./view')` instead of `this.render('./view.njk')`

Let me know if this helps :1st_place_medal:

**Comment by farzer** [comment]
thanks
