### ISSUE TITLE
I want to keep to maintain this project

### ISSUE THREAD

**Issue by int64ago** [queckezz/koa-views#86]
Hi, thanks for this great job! My project [moky](https://github.com/int64ago/moky) use koa-views (for some personal purpose, I forked one). As I see, you added a maintainers-wanted badge, and I think I have enough time to keep maintaining this project :-)

Thanks

**Comment by queckezz** [comment]
Thanks, I'll added you as a maintainer! Just make sure you always lint your changes by running `npm run lint` to keep a uniform code style.
