### ISSUE TITLE
Don't compile to ES5 ?

### ISSUE THREAD

**Issue by int64ago** [queckezz/koa-views#89]
Hi, koa v2.0 has been released and it requires Node v7.6+ (which supports sync functions natively). I think koa-views doesn't need to support Node with low version, it losses some performance.

**Comment by queckezz** [comment]
Yea I think we can remove it since we don't depend on other es2016 features which arent supported by node 7.6+. Should we pin koa as a peer dep so it fails for koa versions under 2.x?

**Comment by int64ago** [comment]
Yes, this's better!

**Comment by queckezz** [comment]
Closed via #90

**Comment by tangdaohai** [comment]
so, in the last version, if I use node LTS version I will get an  exception, right?

**Comment by int64ago** [comment]
@tangdaohai Yes, if you deploy without Babel (of course, Koa2 can't work neither)

**Comment by tangdaohai** [comment]
@int64ago  I not deploy without babel, and my server can't work, because I use koa-views last version...  all right, get it back to version 6.0

**Comment by int64ago** [comment]
[Koa2 requires Node v7.6+](https://github.com/koajs/koa#installation), and koa-views only supports Koa2.

**Comment by tangdaohai** [comment]
@int64ago thanks, I knows this. koa-views  back to 6.0 version. my server working, thank you
