### ISSUE TITLE
Render() failed when given a directory and using non-HTML extension

### ISSUE THREAD

**Issue by gnituy18** [queckezz/koa-views#91]
I use `pug` as my default extension for my views.
And I structure my `views` dir like this:
```
views/dirA/index.pug
views/dirA/_include.pug
views/dirB/index.pug
```

```javascript
app.use(views(__dirname + '/views', {'extension': 'pug'}))

app.use(async function (ctx) {
  await ctx.render('dirA')
})
```
I want to render `dirA/index.pug` just by passing `dirA` , but I got a error like this:
```
Error: ENOENT: no such file or directory, open '/blah/blah/blah/app/views/dirA/dirA/index.pug'
at Object.fs.openSync (fs.js:582:18)
      ........
      ........
      ........
at /blah/blah/blah/app/node_modules/koa-views/lib/index.js:53:20
```
Without the extension, everything works fine.
So when I go further... I think that 
```javascript
// koa-views/src/index.js:64
abs: join(abs, dirname(rel), rel),
```
is what causes `.../views/dirA/dirA/index.pug` got 2 `dirA`
```javascript
// koa-views/src/index.js:46
return render(resolve(paths.abs, paths.rel), state)
```

**Comment by int64ago** [comment]
Hi, do you use the latest version ?

**Comment by gnituy18** [comment]
Yes. I'm using 6.0.0

**Comment by int64ago** [comment]
Hi, I think cfe2202a39de6b0ceea27b9618bccc640a319537 fixes the BUG

But I have no permission for npm publishing, please wait for @queckezz

**Comment by queckezz** [comment]
Thanks for the fast fix! @int64ago. You should now be able to publish new versions :sparkles:

![image](https://cloud.githubusercontent.com/assets/2580598/23800204/b175bcb4-05ab-11e7-9348-c5bf06a67a8a.png)

**Comment by int64ago** [comment]
@queckezz Thx :-)

@gnituy18 Now, you can check v6.0.1, thanks for your patience
