### ISSUE TITLE
Question: global variable in view file

### ISSUE THREAD

**Issue by raphaelsoul** [queckezz/koa-views#97]
How can I access `ctx` in a view file?
For example, I want to visit `ctx.state.user` in a `.hbs` file.
is there some way globally passing some value? Thanks

**Comment by int64ago** [comment]
What do you mean `global variable`? Does `await ctx.render('user.hbs', { user: ctx.state.user })` work for you?

**Comment by raphaelsoul** [comment]
my bad. I use `passport` to authenticate my visitors. And I found I can use `{{ user }}` to access my `ctx.state.user`.
